allowBuilds:
  sharp: true
  unrs-resolver: true
overrides:
  "brace-expansion@>=2.0.0 <2.1.4": 2.1.4
  "glob@>=10.2.0 <10.5.0": 10.5.0
  "minimatch@>=9.0.0 <9.0.9": 9.0.9
  "picomatch@<2.3.2": 2.3.2
  "postcss@<8.5.23": 8.5.23
  "yaml@>=2.0.0 <2.8.3": 2.9.0
